### ISSUE TITLE
Thread Safety Concerns with gilrs and audio_player

### ISSUE THREAD

**Issue by silverhadch** [Amjad50/plastic#17]
There is no mention of locking or managing concurrent access to shared resources like the gilrs gamepad instance and audio_player. If accessed from multiple threads, this could cause undefined behavior.

Ensure thread safety using appropriate synchronization mechanisms (e.g., Mutex or RwLock).

**Comment by Amjad50** [comment]
But there is no thread safety concerns because there is no threads here.

I don't see a point of concurrency if there is nothing running concurrently.

This tui binary is just a binary, i.e. others can't use it as a dependancy and introduce threading issues.

**Comment by silverhadch** [comment]
Yeah forgot
