### ISSUE TITLE
Unwrapping on gilrs::new()

### ISSUE THREAD

**Issue by silverhadch** [Amjad50/plastic#18]
The gilrs: Gilrs::new().unwrap(); could panic if the gamepad interface cannot be initialized (e.g., missing drivers or unsupported hardware).

Replace .unwrap() with a more graceful fallback, like logging the error and continuing without gamepad support.

**Comment by inyourface34456** [comment]
i could take this issue

**Comment by Amjad50** [comment]
Implemented in #43
