### ISSUE TITLE
Potential Memory Leaks with File Explorer

### ISSUE THREAD

**Issue by silverhadch** [Amjad50/plastic#19]
The FileExplorer::with_theme(theme).unwrap() could leak memory if the theme object or internal state is not properly managed.

Review how FileExplorer handles its internal state and ensure that resources are properly cleaned up when the explorer is closed or destroyed.

**Comment by Amjad50** [comment]
I really not sure what you mean by leaking here, the `FileExplorer` is used throughout the app lifetime, we just control if we render it or not, the object isn't destroyed, so nothing is leaked.

**Comment by silverhadch** [comment]
Yes i didnt look at the entire Codebase just the TUI.
