### ISSUE TITLE
I am adding a Desktop File but the icon location would be nice.

### ISSUE THREAD

**Issue by silverhadch** [Amjad50/plastic#31]
Where is the icon stored and if no where please store it in .local/share/plastic so i can make the icon actually appaer in the app launcher

**Comment by Amjad50** [comment]
The icon is at [images/icon.png](https://github.com/Amjad50/plastic/blob/master/images/icon.png). 

For the `desktop` file we can do something like this: https://github.com/xlmnxp/blue-recorder

**Comment by silverhadch** [comment]
> The icon is at [images/icon.png](https://github.com/Amjad50/plastic/blob/master/images/icon.png).
> 
I meant post-install. I want to make an .desktop file for applaunchers because a GUI Application without doesnt make sense. While i could PR the current one but an Icon would be nice.

**Comment by silverhadch** [comment]
this is the current desktop file. The location of the binary is the standard since its installed by cargo, however the icon is not. 
[Desktop Entry]
Version=1.1
Type=Application
Name=Plastic - NES
Comment=Plastic - NES Emulator
Icon=~/.cargo/icons/icon.png
Exec=~/.cargo/bin/plastic
Actions=
Categories=Game;

**Comment by Amjad50** [comment]
I'm thinking we can use [`cargo dep`](https://github.com/kornelski/cargo-deb) i.e. provide some options on the assets installation in `Cargo.toml` and then make package maintainers use that as a reference (for example for the current Arch installation).

`cargo install` doesn't provide any functionality to install custom `.desktop` files, so we can ignore it for this purpose.

Also CC: @orhun if you have extra input.

**Comment by silverhadch** [comment]
@orhun since you mantain the Arch Package have you made a .desktop file for the Applaunchers in the PKGBUILD with the icon???

**Comment by silverhadch** [comment]
@Amjad50 i made a debian package that does it automatically for Debian and Ubuntu. I will submit it to the official repo maybe today or tomorrow.

**Comment by orhun** [comment]
The Arch package does not contain the desktop file yet - mainly because it is not in the repo. It would be nice to add it here first so that I can update the package :)

**Comment by marcelarie** [comment]
@silverhadch @orhun I made a [PR](https://gitlab.archlinux.org/archlinux/packaging/packages/plastic/-/merge_requests/1) in the GitLab Arch Linux repo to add the `.desktop` entry and icon.

It could be easier for future contributions if the `PKGBUILD` and related files were in this GitHub repo, but that is a matter of preference.

**Comment by silverhadch** [comment]
> I think those asses should be the part of the repo and the Arch package should simply install them. Are they added to here yet?

@orhun i created them universally in mind for the Debian Package. Everything you need is in the repo.
Exact Locations.

Manpage:
docs/man/plastic.1

Desktop File:
package/plastic.desktop

Icon (in the desktop file its renamed to plastic-icon.png):
Images/icon.png

**Comment by marcelarie** [comment]
> I think those asses should be the part of the repo and the Arch package should simply install them. Are they added to here yet?

Agree. We even could add the `PKGBUILD` to be part of the repo, then we could point to the Arch Linux repository as a remote. Thoughts?

**Comment by marcelarie** [comment]
My bad, I did not check properly. Will update the PR now 👌
